CREATE TABLE IF NOT EXISTS Z_ANALYSISREPORTS
(
    id      BIGINT(20) UNSIGNED NOT NULL AUTO_INCREMENT,
    md5hash VARCHAR(40) NOT NULL,
    PRIMARY KEY (id),
    KEY IDX_MD5HASH(md5hash)
);

CREATE TABLE IF NOT EXISTS Z_SLOWQUERYLOGS
(
    id        BIGINT(20) UNSIGNED NOT NULL AUTO_INCREMENT,
    report_id INT(10) UNSIGNED NOT NULL,
    log_entry JSON NOT NULL,
    PRIMARY KEY (id),
    KEY IDX_REPORT_ID(report_id)
);