services:

  mysql:
    image: appkr/mysql:8.0-arm64
    container_name: mysql
    volumes:
      - $HOME/mysql_data8:/var/lib/mysql/
      - $HOME/mysql_log8:/var/log/mysql/
      - ./mysqld.cnf:/tmp/mysqld.cnf
    environment:
      - MYSQL_ROOT_PASSWORD=secret
    ports:
      - 3306:3306
    command: mysqld --defaults-extra-file=/tmp/mysqld.cnf
    healthcheck:
      test: mysql -uroot -psecret -e 'SELECT 1' 2>/dev/null || exit 1
