name: Build and Prerelease

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-java@v3
        with:
          distribution: 'corretto'
          java-version: '17'

      - name: Build with gradle
        run: ./gradlew clean build

      - name: Upload jar
        uses: actions/upload-artifact@v3
        with:
          name: jar
          path: |
            tools-spring-boot-starter/build/libs/*.jar
          retention-days: 1

        # TODO @appkr: gpg: signing failed: No secret key
        # Reference: https://central.sonatype.org/publish/
        # Reference: https://maciejwalkowiak.com/blog/guide-java-publish-to-maven-central/
        # Reference: https://docs.gradle.org/current/userguide/signing_plugin.html
        # SNAPSHOT repository: https://s01.oss.sonatype.org/content/repositories/snapshots/dev/appkr/tools/
#      - name: Publish to Maven Central
#        uses: gradle/gradle-build-action@v2
#        with:
#          arguments: publish -x check -Psigning.gnupg.executable=gpg -Psigning.gnupg.keyName=${{ secrets.GPG_KEY_NAME }} -Psigning.gnupg.passphrase=${{ secrets.GPG_PASSPHRASE }}
#        env:
#          OSSRH_USER: ${{ secrets.OSSRH_USER }}
#          OSSRH_PASS: ${{ secrets.OSSRH_PASS }}
#          GPG_KEY_NAME: ${{ secrets.GPG_KEY_NAME }}
#          GPG_PASSPHRASE: ${{ secrets.GPG_PASSPHRASE }}

  # Reference: https://electricui.com/blog/github-actions
  release:
    name: Create prerelease
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/download-artifact@v3

      - name: Display fetched artifacts
        run: ls -alR .

      - name: Create a github release
        uses: marvinpinto/action-automatic-releases@latest
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          automatic_release_tag: latest
          prerelease: true
          title: Development Build
          files: |
            jar/*.jar
